source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
swift_version = '3.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'NewsAppSwiftMVVM' do
  #Rx
  pod 'RxSwift',    '~> 3.0.0'
  pod 'RxCocoa',    '~> 3.0.0'
  #Realm
  pod 'RealmSwift'
  #Alamofire
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'SDWebImage',    '~> 3.8'
end

target 'NewsAppSwiftMVVMTests' do
  #Rx
  pod 'RxSwift',    '~> 3.0.0'
  pod 'RxCocoa',    '~> 3.0.0'
  #Realm
  pod 'RealmSwift'
  #Alamofire
  pod 'Alamofire'
  pod 'RxAlamofire'
  # Pods for testing  
  pod 'RxBlocking'
  #pod 'RxTests',    '~> 2.0'
  pod 'SDWebImage',    '~> 3.8'
end

target 'NewsAppSwiftMVVMUITests' do

end
