source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'NewsAppSwiftMVVM' do
  pod 'FontAwesomeKit', '~> 2.2.0'
  #Rx
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'
  #Realm
  pod 'RealmSwift'
  #Alamofire
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'SDWebImage',    '~> 3.7'
end

target 'NewsAppSwiftMVVMTests' do
  pod 'FontAwesomeKit', '~> 2.2.0'
  #Rx
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'
  #Realm
  pod 'RealmSwift'
  #Alamofire
  pod 'Alamofire'
  pod 'RxAlamofire'
  # Pods for testing  
  pod 'RxBlocking', '~> 2.0'
  pod 'RxTests',    '~> 2.0'
  pod 'SDWebImage',    '~> 3.7'
end

target 'NewsAppSwiftMVVMUITests' do

end

